language: python

# No python2!
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.10 DJANGO_SETTINGS_MODULE=shop.test_settings

before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y

install:
  - pip install -q Django==$DJANGO
  - pip install -q .
  - pip install -qr requirements.txt
  - pip install coveralls

script:
    coverage run --source=shop python manage.py test

after_success:
    coveralls
